### ISSUE TITLE
Some problems with Brax Environment Training

### ISSUE THREAD

**Issue by davidkillerhahaha** [wuwushrek/physics_constrained_nn#1]
Hello,
We tried to run this version of codes and found it all goes well with double pendulum env, but had some problems we cannot solve with  Brax Environment Training. For example:
1. ImportError: cannot import name 'vec_to_np' from 'brax.physics.base' or ModuleNotFoundError: No module named 'brax.physics.math' and etc. We can replace 'vac_to_arr' with 'vec_to_np'  and replace 'from brax.math import ang_to_quat, euler_to_quat' with current version. I don't know if it caused by the update of Brax ? Some more problems in 'utils_brax.py'...
2. `Traceback (most recent call last):
  File "/home/nifei/anaconda3/envs/pinntest/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nifei/anaconda3/envs/pinntest/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nifei/working/physics_constrained_nn/examples/brax/generate_sample.py", line 248, in <module>
    main_fn(args.cfg, m_config_aux)
  File "/home/nifei/working/physics_constrained_nn/examples/brax/generate_sample.py", line 134, in main_fn
    pos_indx, quat_indx, rot_indx = utils_brax.index_active_posrot(env.sys)
  File "/home/nifei/working/physics_constrained_nn/physics_constrained_nn/utils_brax.py", line 41, in index_active_posrot
    pos_indx = brax_sys.active_pos.astype(bool)
AttributeError: 'System' object has no attribute 'active_pos'`
This error we met is so strange and could you help with us please?

**Comment by Jin0932** [comment]
Hello, 

 I also meet error "ImportError: cannot import name 'kinetic' from 'brax.physics.integrators' ", and how I solve this question?

( Jax) User@DL:~/experiment/physics_constrained_nn/examples/brax$ python generate_sample.py --cfg reacher_brax/dataset_gen.yaml --output_file /home/User/experiment/physics_constrained_nn/examples/brax
Traceback (most recent call last):
  File "generate_sample.py", line 13, in <module>
    from physics_constrained_nn import utils_brax
  File "/home/User/experiment/physics_constrained_nn/physics_constrained_nn/utils_brax.py", line 10, in <module>
    from brax.physics.integrators import kinetic, potential
ImportError: cannot import name 'kinetic' from 'brax.physics.integrators' (/home/User/experiment/brax/brax/physics/integrators.py)


My environment:
jax                       0.3.14                   pypi_0    pypi
jaxlib                    0.3.14+cuda11.cudnn82          pypi_0    pypi
